### Site Settings ###
title               : Suparna's Blog
description         : >-
                      Hey, there, I'm Suparna!
                      Welcome to my blog!
                      Learn more about me here!

baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : suparna-here-123/suparna-here-123.github.io    # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Suparna Prasad
  image             : https://www.google.com/url?sa=i&url=https%3A%2F%2Fmetricool.com%2Finstagram-avatar%2F&psig=AOvVaw3Z8-WqMRoB5lE7yQBkzdSE&ust=1723362266750000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCKC5je326YcDFQAAAAAdAAAAABAE
  email             : pes1202201025@pesu.pes.edu
  github            : suparna-here-123
  linkedin          : suparna-prasad

### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id



### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"